FROM mysql:latest
LABEL MAINTAINER="Weiqing Huang <wqhuang.ustc@gmail.com>"
ENV MYSQL_ROOT_PASSWORD=eficode2019
#COPY setup.sh /mysql/setup.sh
#COPY sql/*.sql /docker-entrypoint-initdb.d/
#CMD ["sh", "/mysql/setup.sh"]
