version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql:/var/lib/mysql

  opendata:
    image: kylinhuang/opendata:latest
    container_name: opendata
    ports:
      - 8080:8080
      - 3000:3000


volumes:
  mysql:
